### ISSUE TITLE
Hyjax summary

### ISSUE THREAD

**Issue by tpluscode** [pajax/hyjax#3]
Hi. I found your library through a link in hydra-cg. I was going to implement something similar myself but it's best if such efforts were unified. Could you please write a short summary on what is implemented in hyjax already?

**Comment by vanthome** [comment]
Hi Tomasz, 
Thomas here, from the hydra mailing list ;)
We only recently published this stuff but have been working on it for years actually.
The current status is:

- with pajax 0.5 (soon to be released) we will have a excellent and stable fetch() compatible basis for hyjax. This is a big plus as we found that there are very subtle problems that can best be solved with something like fetch() w/o reinventing the wheel.
- Api-Doc support is based on a custom format that we implemented in an unpublished server project. We want to turn this into fully fledged Hydra Core API doc support
- collection meta data and introspection support
- **missing** pagination support. Should be easy to implement though.

So overall it's not yet Hydra Core compliant and that's why I did not announce it on the mailing list yet.

I would be more than happy, if you would help us and/ or base your stuff on this lib.

BG, Thomas

**Comment by tpluscode** [comment]
Hi Thomas :)
I've just tried hyjax and I find that it doesn't behave in the way I expected.

The first thing I notice is how the flow is that given `new Hyjax('http://example.api')`, the library tries to fetch some predefined `/application` url for documentation and the redirects to `/resources`. Is this a convention you follow in you custom api-doc?

**Comment by vanthome** [comment]
@tpluscode 

Yea, that's what I meant with the second point "Api-Doc support is based on a custom format". Conceptually this does the same think as API-Doc would do, it just needs to be migrated.
We just did not implement/ migrate it yet as our server is able to provide both.
Please feel free to implement this in a branch ;)
